#ifndef GRAPH3D_CORE_CONTEXT_TYPE_H_
#define GRAPH3D_CORE_CONTEXT_TYPE_H_

namespace graph3d {
enum ContextType { G3D_CONTEXT_WINDOW, G3D_CONTEXT_MONITOR, G3D_CONTEXT_VIEWPORT, G3D_CONTEXT_SHADER };
}

#endif